apiVersion: v1
kind: Service
metadata:
  name: junit-app-test
  labels:
    app: junit-app-test

spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: junit-app-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: junit-app-test
  labels:
    app: junit-app-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: junit-app-test
  template:
    metadata:
      labels:
        app: junit-app-test
    spec:
      containers:
      - name: springbootapp
        image: sreelk589/junit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
